#!/bin/bash

loc=$1


case $2 in

        "add"  )
                case $3 in
                
                        "list" )
                                case $4 in 

                                "git"  )
                                $loc/build-frame.sh $5 $6 $7 cusgit $8
                                ;;

                                "folder" )
                                $loc/build-frame.sh $5 $6 $7 cusfol $8
                                ;;
                                
                                esac
                        ;;

                        "folder" )
                        $loc/build-frame.sh $4 $5 $6 dir 
                        ;;

                        "git" )
                        $loc/build-frame.sh $4 $5 $6 git
                        ;;
                
                esac
        ;;

        "make" )
                case $3 in
                        $nothing )
                        $loc/make.sh
                        ;;

                        * )
                        $loc/make.sh $3
                        ;; 
                esac
        ;;

        "new" )
                case $3 in 

                "list" )
                $loc/newlist.sh $4
                ;;
                esac
        ;;
        "delete" )
                case $3 in

                $nothing ) 
                echo 
                ;;
                
                * )
                        
                $loc/cutter.sh $3 $4

        
                ;;

                esac
        ;;

        "remove" )

                


        ;;


        "clear" )
                $loc/cutter.sh $2 $3 $4 $5 $6 $7 $8 $9
        ;;


        "show"  )
                $loc/show.sh $3 $4 $5 $6 $7 $8 $9 
        ;;
esac