#!/bin/bash

loc=$1

case $2 in

        "add"  )
                case $3 in
                
                        "list" )
                
                                case $5 in 

                                "git"  )
                        
                                        $loc/build-frame.sh $6 $7 $8 cusgit $4
                        
                                ;;

                                "folder" )
                        
                                        $loc/build-frame.sh $6 $5 $8 cusfol $4
                        
                                ;;
                                
                                esac
                
                        ;;

                        "folder" )
        
                                $loc/build-frame.sh $4 $5 $6 dir 
        
                        ;;

                        "git" )

                                $loc/build-frame.sh $4 $5 $6 git

                        ;;
                
                esac

        ;;

        "make" )

                case $3 in

                        $nothing )
                        
                                $loc/make.sh

                        ;;

                        * )

                                $loc/make.sh $3

                        ;; 

                esac

        ;;

        "new" )

                case $3 in 

                        "list" )
                        
                                $loc/newlist.sh $4
                
                        ;;

                esac
        ;;

        "delete" )

                case $3 in

                $nothing ) 
        
                        echo o-o
                
                ;;
                
                * )
                        
                        $loc/cutter.sh $3 $4
        
                ;;

                esac
        
        ;;

        "clear" )
                
                $loc/cutter.sh $2 $3 $4 $5 $6 $7 $8 $9
      
        ;;

        "show"  )
     
                $loc/show.sh $3 $4 $5 $6 $7 $8 $9 
     
        ;;

        "help" )
     
                cat ../build-help/help
     
        ;;

        "run" )
                case $3 in
                        
                        $nothing )
     
                                ../../builder.sh
     
                        ;;
                        
                        * )
                                
                                ../build-custom/$3/$3-builder.sh
                                
                        ;;

                esac
        ;;

        "install" )

                ../../install.sh

        ;;

        "data" )

                ./import-export.sh $loc $3 $4 $5 $6 $7 $8 $9

        ;;

esac