#!/bin/bash

loc=$1

case $2 in

        "add"  )
                
                case $3 in

                        "help" )

                                cat ../build-help/help-add

                        ;;

                        "auth" )

                                $loc/auth.sh $4 $5 $6 $7 $8 $9
                        
                        ;;

                        * ) 
                
                               $loc/build-frame.sh $4 $5 $6 $7 $8 $9      
                
                        ;;

                esac 

        ;;

        "make" )

                case $3 in

                        * )

                                $loc/make.sh $3 $4 $5 $6 $7 $8 $9

                        ;; 

                esac

        ;;

        "new" )

                case $3 in 

                        "list" )
                        
                                $loc/newlist.sh $4 $5 $6 $7 $8 $9 
                
                        ;;

                        "help" )

                                cat ../build-help/help-new

                        ;;

                esac

        ;;

        "delete" )

                case $3 in
                
                * )
                        
                        $loc/cutter.sh $3 $4
        
                ;;

                esac
        
        ;;

        "clear" )
                
                $loc/cutter.sh $2 $3 $4 $5 $6 $7 $8 $9
      
        ;;

        "show"  )
     
                $loc/show.sh $3 $4 $5 $6 $7 $8 $9 
     
        ;;

        "help" )
     
                cat ../build-help/help
     
        ;;

        "run" )
                case $3 in
                        
                        "help" )

                                cat ../build-help/help-run
                        
                        ;;
 
                        "list" )

                                $loc/run.sh $4 $5 $6 $7 $8 $9

                        ;;


                        * )
                                
                                ../build-custom/$3/$3-builder.sh
                                
                        ;;

                esac

        ;;

        "install" )

                ../../install.sh

        ;;

        "data" )

                ./import-export.sh $loc $3 $4 $5 $6 $7 $8 $9

        ;;

        "edit" )

                case $3 in 

                        $nothing )

                                nano ../build-custom/cron-config.txt

                        ;;

                        * )

                                case $4 in 

                                        $nothing )

                                                echo 'the command reqiures a frame to edit'
                                        
                                        ;;
                                        
                                        * )

                                                nano ../build-custom/$3/build-list/$4

                                        ;;

                                esac

                        ;;
                
                esac
                
        ;;

esac