#!/bin/bash

#Not yet functioning 

list=$1

frame=$2

echo '#!/bin/bash' >> ..
cat .config/varibles >> ../temp.sh
cat ../build-custom/$list/$frame >> ../temp.sh
echo "mikua clear list $list frame $frame" >> ../temp.sh
echo 'mikua add list $list $name $link' >> ../temp.sh
chmod u+x ../temp.sh
/temp.sh
rm ../temp.sh