version: "3"

services:
 
  mikua:

    container_name: mikua

    image: miku-yta

    volumes:
      - ./data:/downloads
      - ./config:/git/build-info/build-custom

    restart: unless-stopped

    stdin_open: true 
    tty: true