version: "3"

services:
   mikua:
    container_name: mikua
    image: kingregailya/mikua
    volumes:
      - ./data:/downloads
      - 'mikua-config:/mikua/build-info/build-custom'
    restart: unless-stopped
    stdin_open: true 
    tty: true

volumes:
  mikua-config: