FROM ubuntu
RUN apt update

#install dependises 
RUN apt install apt-utils
RUN apt -y install nano curl python3 ffmpeg zip cron
RUN apt-get update && apt-get install -y git

#installs YT-DLP
RUN curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp
RUN chmod a+rx /usr/local/bin/yt-dlp
RUN mkdir /downloads

#installs mikua
COPY build-info /mikua/build-info 
COPY mikua /bin/mikua
RUN chmod u+x /bin/mikua 
RUN chmod u+x /mikua/build-info/build-tools/*

#Makes cron 
COPY cron-config /etc/cron.d/cron-config
RUN chmod 0644 /etc/cron.d/cron-config
RUN crontab /etc/cron.d/cron-config
RUN touch /var/log/cron.log
CMD cron && tail -f /var/log/cron.log
RUN chmod u+x /mikua/build-info/build-custom/tasks.sh

#Tells mikua weather this is installed on OS or Docker
RUN echo docker >> /mikua/build-info/version-installed